name: Hello World
description: A Hello World GitHub Action example with Pydantic.
inputs:
  name:
    description: Who to greet
    default: World
  title:
    description: Honorific prefix
outputs:
  greeting:
    description: Greeting

runs:
  using: docker
  image: Dockerfile
  entrypoint: /opt/app/action.py
