name: Hello World
description: A Hello World GitHub Action example with Python
  with outputs.
inputs:
  name:
    description: Who to greet.
    default: World
outputs:
  greeting:
    description: Greeting

runs:
  using: docker
  image: Dockerfile
  entrypoint: /opt/app/action.py
