name: HTTP Status Cats
description: A GitHub action example using HTTP Status Cats
  using Pydantic validation!
inputs:
  http_code:
    description: HTTP Status Code
    required: true
  api_token:
    description: API Token
    required: true
outputs:
  title:
    description: HTTP status code title
  image:
    description: Image URL
  data:
    description: JSON response
runs:
  using: docker
  image: Dockerfile
  entrypoint: /opt/app/action.py
