name: Action

on:
  workflow_call:
    inputs:
      http_code:
        description: HTTP Status Code
        required: true
        type: string
    secrets:
      api_token:
        description: API Token
        required: true
  workflow_dispatch:
    inputs:
      http_code:
        description: HTTP Status Code
        default: "100"
      api_token:
        description: API Token
        default: APIKEY

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: httpcat
        uses: ./
        with:
          http_code: ${{ inputs.http_code }}
          api_token: ${{ inputs.api_token }}${{ secrets.api_token }}
      - run: echo 'Description - ${{ steps.httpcat.outputs.description }}'
      - run: echo 'Image - ${{ steps.httpcat.outputs.image }}'
