name: CI

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  run:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [pre-commit, mypy]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: python
      - uses: actions/cache@v3
        with:
          path: |
            .mypy_cache
            .ruff_cache
            .tox
            ~/.cache/pip
            ~/.cache/pre-commit
          key: tox-${{ runner.os }}-py${{ steps.python.outputs.python-version }}-${{
            matrix.env }}-${{ hashFiles('pyproject.toml', 'requirements.txt', 'tox.ini') }}
      - name: Run tox
        run: pipx run 'tox~=4.2'
        env:
          RUFF_FORMAT: github
          TOXENV: ${{ matrix.env }}
