name: Container

on:
  push:
    paths:
      - Containerfile
      - "**.py"
      - pyproject.toml
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-container
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - run: sudo sh -c
          'apt-get -qq update && apt-get install -y qemu-user-static'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        id: py
        with:
          cache: pip
          cache-dependency-path: constraints.txt
      - name: Get build-arg values
        id: build-arg
        run: |
          python3 -m pip install setuptools_scm
          echo "VERSION=$(python3 -m setuptools_scm)" >> "$GITHUB_OUTPUT"
          echo "PIP_CACHE=$(python3 -m pip cache --format abspath dir)" >> "$GITHUB_OUTPUT"
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          flavor: latest=false
          tags: |
              type=ref,event=branch
              type=ref,event=tag
              type=sha
              type=raw,value=latest,enable={{is_default_branch}}
      - uses: redhat-actions/buildah-build@v2
        id: build
        with:
          archs: amd64, arm64, arm
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: Dockerfile
          oci: true
          extra-args: |
            --volume=${{ steps.build-arg.outputs.PIP_CACHE }}:/root/.cache/pip
            --build-arg=VERSION=${{ steps.build-arg.outputs.VERSION }}
            --build-arg=PY_VER=${{ steps.py.outputs.python-version }}
      - run: buildah inspect ${{ steps.build.outputs.image-with-tag }} | jq .
      - run: podman container run --rm ${{ steps.build.outputs.image-with-tag }} --help
      - uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" << EOL
          ## Container Details
          - Image:
            \`podman image pull ${{ steps.build.outputs.image-with-tag }}\`
          - Tags:
            ${{ steps.build.outputs.tags }}
          - Pushed to:
            $(jq -r '.[]' <<< '${{ steps.push.outputs.registry-paths }}')
          - Digest: ${{ steps.push.outputs.digest }}
          EOL
