name: Container

on:
  push:
    paths:
      - Containerfile
      - "**.py"
      - pyproject.toml
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-container
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - run: sudo sh -c
          'apt-get -qq update && apt-get install -y qemu-user-static'
      - uses: actions/setup-python@v4
        id: py
        with:
          cache: pip
          cache-dependency-path: constraints.txt
      - run: python3 -m pip install setuptools_scm
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          flavor: latest=false
          tags: |
              type=ref,event=branch
              type=ref,event=tag
              type=sha
              type=raw,value=latest,enable={{is_default_branch}}
      - uses: redhat-actions/buildah-build@v2
        id: build
        with:
          # archs: amd64, arm64, arm
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: Containerfile
          oci: true
          extra-args: |
            --volume="$(python3 -m pip cache --format abspath dir):/root/.cache/pip"
            --build-arg="VERSION=$(python3 -m setuptools_scm)"
            --build-arg='PY_VER=${{ steps.py.outputs.python-version }}'
      - run: buildah inspect ${{ steps.build.outputs.image-with-tag }} | jq .
      - run: podman run --rm ${{ steps.build.outputs.image-with-tag }} --help
      - uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" << EOL
          ## Container Details
          - Image: ${{ steps.build.outputs.image }}
          - Tags: ${{ steps.build.outputs.tags }}
          - Tagged Image:
            ${{ steps.build.outputs.image-with-tag }}
          - Pushed to:
            ${{ steps.push.outputs.registry-paths }}
          - Digest: ${{ steps.push.outputs.digest }}
          EOL
