name: Demo Hello World 4

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        default: World

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - id: action
        uses: xsc27/github-action-example-python/demo/helloworld/4@trunk
        with:
          name: ${{ inputs.name }}
      - run: echo '# ${{ steps.action.outputs.greeting }}' >> "$GITHUB_STEP_SUMMARY"
